# Generated by Django 5.1.4 on 2025-01-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0003_remove_registerationform_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerationform',
            old_name='password1',
            new_name='password',
        ),
    ]
