# Generated by Django 5.1.4 on 2025-01-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=6)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
    ]
