# Generated by Django 5.1.4 on 2025-01-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_id', models.CharField(max_length=6)),
                ('company_name', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=4)),
                ('Fuel', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='img')),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
