# Generated by Django 5.1.4 on 2025-01-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_vehicle_wheel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
