# Generated by Django 5.1.4 on 2025-01-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
