# Generated by Django 5.1.4 on 2025-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
