# Generated by Django 5.1.4 on 2025-02-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_id_remove_vehicle_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
