# Generated by Django 5.1.4 on 2025-02-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_rename_company_id_vehicle_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
