# Generated by Django 5.1.4 on 2025-02-01 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_contact_email_alter_company_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Vehicle_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('Vehicle_name', models.CharField(max_length=255, null=True)),
                ('Wheel', models.CharField(max_length=5, null=True)),
                ('Year', models.CharField(max_length=4)),
                ('Fuel', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='img')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
