# Generated by Django 5.1.4 on 2025-02-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Company',
            new_name='company',
        ),
    ]
