# Generated by Django 5.1.4 on 2025-02-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_rename_company_vehicle_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
