# Generated by Django 5.1.4 on 2025-02-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_company_id_alter_company_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPARE',
            fields=[
                ('spare_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('spare_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.vehicle')),
            ],
        ),
    ]
